apiVersion: v1
kind: Service
metadata:
  name: static-site-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "alb"  # Use "alb" for Application Load Balancer
spec:
  type: LoadBalancer
  selector:
    app: static-site
  ports:
    - protocol: TCP
      port: 80       # External port exposed to users
      targetPort: 80 # The container's port
